// Datos del equipo y bios provistos por Contexto.Psi (septiembre 2026).

export const coordinators = [
  {
    id: "julieta-pera",
    name: "Lic. Julieta Pera",
    number: "M.N. 68973",
    photo: "/professionals/team/julieta-pera.webp",
    bio: "Psicóloga clínica. Ex concurrente del Hospital Muñiz. Diplomada en Educación Sexual Integral y Equidad de Género y Políticas Públicas. Formada en Psicoterapia Analítico Funcional (FAP) y Terapias de Tercera Ola (ACT, DBT, RO-DBT) y TDAH en adultxs. Creadora y coordinadora del espacio Encuentros Neurodivergentes.",
  },
  {
    id: "liza-murlender",
    name: "Lic. Liza Murlender",
    number: "M.N. 70026",
    photo: "/professionals/team/liza-murlender.webp",
    bio: "Licenciada y Profesora en Psicología (UBA). Con una perspectiva integrativa, es diplomada en Terapias contextuales (IPPC; ACT-FAP en F. Validar), Trauma (CACT), Género y Educación Sexual Integral (UNSAM). Trabaja también como Consultora y Capacitadora en el ámbito organizacional y laboral.",
  },
  {
    id: "sol-leibgorin",
    name: "Lic. Sol Leibgorin",
    number: "M.N. 69481",
    photo: "/professionals/team/sol-leibgorin.webp",
    bio: "Psicóloga Clínica Integrativa, especializada en Sexología Clínica y diplomada en Educación Sexual Integral. También se desempeña en el ámbito de la Psicología Educativa.",
  },
  {
    id: "luciana-conti",
    name: "Lic. Luciana Conti",
    number: "M.N. 69515",
    photo: "/professionals/team/luciana-conti.webp",
    bio: "Especialista en Psicología Clínica. Ex-concurrente del Hospital de Niños Dr. Ricardo Gutiérrez. Diplomada en Problemáticas actuales infanto-juveniles. Formada en DBT para adolescentes y familias y en psicoterapia con psicodélicos.",
  },
  {
    id: "tatiana-galinsky",
    name: "Lic. Tatiana Galinsky",
    number: "M.N. 69655",
    photo: "/professionals/team/tatiana-galinsky.webp",
    bio: "Psicóloga Clínica (UBA) de adultxs y parejas. Trabaja desde una perspectiva integral. Diplomada en Educación Sexual Integral y diversidad. Diplomada en terapias contextuales y de tercera generación: ACT, DBT, Terapia Integral de Pareja (IBCT) y Regulación Emocional (RO DBT).",
  },
];

export const professionals = [
  {
    id: "florencia-alvarez-martinez",
    name: "Lic. Florencia Alvarez Martinez",
    number: "M.N. 76412",
    photo: "/professionals/team/florencia-alvarez-martinez.webp",
    bio: "Lic. en Psicología (UBA). Formada en técnicas conductuales y en terapia cognitivo-conductual (CETECIC), con diplomatura en trastornos de ansiedad, estrés y depresión (UCES). Actualmente cursa la especialización en Psicología Clínica y Terapia Cognitivo-Conductual (UBA).",
  },
  {
    id: "julieta-arriola",
    name: "Lic. Julieta Arriola",
    number: "M.N. 65610",
    photo: "/professionals/team/julieta-arriola.webp",
    bio: "Psicóloga clínica de niñxs, adolescentes y adultxs, con orientación psicoanalítica. Ex-concurrente del Hospital de niños Ricardo Gutiérrez.",
  },
  {
    id: "magali-bergera",
    name: "Lic. Magalí Bergera",
    number: "M.N. 63302",
    photo: "/professionals/team/magali-bergera.webp",
    bio: "Psicóloga, dedicada a la clínica psicoanalítiac y a la investigación en ese campo. Ex-concurrente del Hospital Borda. Trabajó varios años en un dispositivo de abordaje de problemáticas de consumo y en un centro de atención integral orientado a mujeres.",
  },
  {
    id: "stefania-carancini",
    name: "Lic. Stefanía Carancini",
    number: "M.N. 71160",
    photo: "/professionals/team/stefania-carancini.webp",
    bio: "Psicóloga (Universidad del Salvador), con Máster en Psicoterapia Cognitiva Integrativa (Fundación Aigle) y doble titulación en Argentina y España. Formación clínica con fellowship en el Hospital de Clínicas de Buenos Aires. Se especializa en el tratamiento de la ansiedad, la depresión y el acompañamiento en crisis vitales.",
  },
  {
    id: "rocio-diaz",
    name: "Lic. Rocío Díaz",
    number: "M.P. 14758",
    photo: "/professionals/team/rocio-diaz.webp",
    bio: "Psicóloga conductual-contextual. Formada en Terapia de Aceptación y Compromiso (ACT), Psicoterapia Analítico Funcional (FAP), Terapia Dialéctico Conductual (DBT) y Terapia Integral Conductual de Pareja (IBCT), con formación en trauma complejo, depresión y autoestima.",
  },
  {
    id: "mariana-fanello",
    name: "Lic. Mariana Fanello",
    number: "M.N. 68349",
    photo: "/professionals/team/mariana-fanello.webp",
    bio: "Lic. en Psicología (UBA) y Especialista en Psicología Clínica. Trabaja en el ámbito clínico y pericial, desde el psicoanálisis. Realizó la Concurrencia en el Hospital Piñero y capacitaciones en psicoanálisis (ICdeBA, EFBA). Diplomada en Políticas Públicas en Salud Mental y en Clínica y Prevención de las Violencias por Motivos de Género.",
  },
  {
    id: "ayelen-figueroa",
    name: "Lic. Ayelén Figueroa",
    number: "M.N. 78373",
    photo: "/professionals/team/ayelen-figueroa.webp",
    bio: "Licenciada en Psicología con orientación psicoanalítica. Atiende a adolescentes y personas adultas. Formación de posgrado en clínica psicoanalítica (Hospital Ameghino), perspectiva de género, consumos problemáticos y trastornos de la conducta alimentaria. Experiencia en consultorio particular e instituciones de salud mental.",
  },
  {
    id: "silvia-ferreyra",
    name: "Lic. Silvia Ferreyra",
    number: "M.N. 55280",
    photo: "/professionals/team/silvia-ferreyra.webp",
    bio: "Psicóloga especializada en psicoterapia cognitivo-conductual y de tercera generación. Formada en Terapia de Aceptación y Compromiso (ACT) y en DBT, y actualmente en formación como instructora de mindfulness.",
  },
  {
    id: "francisco-herzberg",
    name: "Lic. Francisco Herzberg",
    number: "M.N. 64321",
    photo: "/professionals/team/francisco-herzberg.webp",
    bio: "Licenciado y Profesor en Psicología (UBA). Atiende a personas adultas desde las Terapias Contextuales, con formación en Fundación Foro, Habilidades para el Cambio y CETECIC. Forma parte del equipo de Contexto.Psi desde 2023 como psicólogo y admisor, y también del equipo ICID, brindando atención a personas con discapacidad y con diagnóstico dentro del Espectro Autista.",
  },
  {
    id: "maria-flor-inchauspe",
    name: "Lic. María Flor Inchauspe",
    number: "M.N. 66484",
    photo: "/professionals/team/maria-flor-inchauspe.webp",
    bio: "Psicóloga (UBA), con formación en psicoanálisis y estudios en perspectiva de género, y más de 10 años de experiencia en los ámbitos clínico, educativo e institucional. Atiende a personas adultas desde una orientación psicoanalítica, con un espacio centrado en la singularidad de cada paciente.",
  },
  {
    id: "luciana-zalazar",
    name: "Lic. Luciana Zalazar",
    number: "M.N. 68763",
    photo: "/professionals/team/luciana-zalazar.webp",
    bio: "Psicóloga clínica con enfoque contextual, formada en Terapia de Aceptación y Compromiso (ACT), neurodivergencias y acompañamiento de procesos asistidos con psicodélicos.",
  },
  {
    id: "alejandra-teplitzchi",
    name: "Lic. Alejandra Teplitzchi",
    number: "M.N. 65227",
    photo: "/professionals/team/alejandra-teplitzchi.webp",
    bio: "Licenciada en Psicología (UBA), con concurrencia en el Hospital F. J. Muñiz especializada en clínica psicoanalítica. Diplomada en Salud Mental, Psicoanálisis y Sexología (UBA). Trabaja en consultorio desde el psicoanálisis con perspectiva de género y en el Hospital Muñiz como psicóloga de guardia.",
  },
  {
    id: "antonella-fernandez",
    name: "Lic. Antonella Fernandez",
    number: "M.N. 78322",
    photo: "/professionals/team/antonella-fernandez.webp",
    bio: "Psicóloga (UBA), trabaja principalmente desde la terapia cognitivo-conductual. Formada en Teoría y Terapia Sistémica (Instituto Gregory Bateson), terapia de pareja (Escuela Sistémica Argentina) y DBT (CATC). Cuenta además con formación en duelo y en abordaje del trauma.",
  },
  {
    id: "nicolas-parera",
    name: "Lic. Nicolás Parera",
    number: "M.N. 69818",
    photo: "/professionals/team/nicolas-parera.webp",
    bio: "Psicólogo (UBA) de adolescentes y adultxs, especializado en las áreas clínica y forense. Formado en los Hospitales Ricardo Gutiérrez y Durand. Sus principales temas de interés son psicodiagnóstico, duelo y trauma, desde un abordaje de Psicoanálisis Relacional.",
  },
  {
    id: "camila-lara",
    name: "Lic. Camila Lara",
    number: null,
    photo: "/professionals/team/camila-lara.webp",
    bio: "Licenciada en Psicología con orientación psicoanalítica. Profesora de Enseñanza Media y Superior en Psicología y de Educación Primaria. Maestranda en Psicología Educacional, con diplomatura superior en Diversidad y Educación.",
  },
  {
    id: "sofia-capria",
    name: "Lic. Sofía Capria",
    number: "M.N. 63767",
    photo: "/professionals/team/sofia-capria.webp",
    bio: "Psicóloga clínica integrativa, especializada en Consumos Problemáticos (Universidad Nacional de Tucumán) y formada en Terapias Contextuales (ACT)",
  },
  {
    id: "tabhata-casco",
    name: "Lic. Tabhata Casco",
    number: "M.N. 77173",
    photo: "/professionals/team/tabhata-casco.webp",
    bio: "Terapeuta cognitivo contextual, con perspectiva de género y abocada a la población LGBT+. Formada en DBT (Fundación ECCO; Marea), es coordinadora de talleres de habilidades DBT para mujeres y disidencias (virtual y presencial). Parte del CAOPI de La Casa del Encuentro, ONG en la que atiende víctimas de violencia de género. Especializada en Trastornos de la Conducta Alimentaria (formada en Tandem, La Casita y Modelo Maudsley en DBT Iberoamerica).",
  },
  {
    id: "barbara-ini",
    name: "Lic. Bárbara Ini",
    number: "M.N. 70215",
    photo: "/professionals/team/barbara-ini.webp",
    bio: "Psicóloga clínica. Concurrencia finalizada en Hospital de Niños Dr. Ricardo Gutierrez. Diplomada en “Psicoanálisis y prácticas socioeducativas” y en “Educación Sexual Integral''.",
  },
  {
    id: "camila-larocca",
    name: "Lic. Camila Larocca",
    number: "M.N. 72753",
    photo: "/professionals/team/camila-larocca.webp",
    bio: "Psicóloga especializada en terapias contextuales, vínculos y sexualidad, con perspectiva de género. Acompaña desde una mirada flexible y humana, construyendo espacios profundos y cuidados, explorando también otras formas de encuentro, expresión y construcción colectiva",
  },
  {
    id: "lucila-lavagnino",
    name: "Lic. Lucila Lavagnino",
    number: "M.N. 78314",
    photo: "/professionals/team/lucila-lavagnino.webp",
    bio: "Psicóloga clínica con orientación en psicoanálisis, formada en el ámbito de la salud pública y privada.",
  },
  {
    id: "natali-lipski",
    name: "Lic. Natalí Lipski",
    number: "M.N. 72467",
    photo: "/professionals/team/natali-lipski.webp",
    bio: "Lic. en Psicología (UBA), con orientación psicoanalítica y perspectiva de género. Diplomada en Estudios de Género, Diversidad y Subjetividad, y en Transmisión de Memorias Traumáticas (AASM). Asistió a los Seminarios de Psicoanálisis y Género de la Dra. Débora Tajer. Actualmente se forma en Psicoperinatología psicoanalítica.",
  },
  {
    id: "brenda-lopatka",
    name: "Lic. Brenda Lopatka",
    number: "M.N. 71964",
    photo: "/professionals/team/brenda-lopatka.webp",
    bio: "Psicóloga (UBA) con orientación psicoanalítica. Trabaja con niñxs, adolescentes y adultxs tanto en el ámbito público como privado. Psicóloga y Admisora de Contexto.Psi desde 2020.",
  },
  {
    id: "daniela-ledesma",
    name: "Lic. Daniela Ledesma",
    number: "M.P. 77331",
    photo: "/professionals/team/daniela-ledesma.webp",
    bio: "Atención clínica de personas adultas desde una orientación psicoanalítica con perspectiva de género. Especialización en violencias por motivos de género, salud mental y abordaje interdisciplinario.",
  },
  {
    id: "lucia-moavro",
    name: "Lic. Lucía Moavro",
    number: "M.N. 68467",
    photo: "/professionals/team/lucia-moavro.webp",
    bio: "Psicoanalista (UBA). Especialista en Psicología Clínica con orientación psicoanalítica y Especialista en Psicología Clínica Infanto-Juvenil, formada en el Hospital de Niños Dr. R. Gutiérrez.",
  },
  {
    id: "victoria-nunez",
    name: "Lic. Victoria Nuñez",
    number: "M.N. 59247",
    photo: "/professionals/team/victoria-nunez.webp",
    bio: "Psicóloga. Psicoanalista. Diplomada en sexualidad y terapias sexuales.",
  },
  {
    id: "veronica-percara",
    name: "Lic. Verónica Percara",
    number: "M.N. 67069",
    photo: "/professionals/team/veronica-percara.webp",
    bio: "Lic. en Psicología (UBA), con formación de posgrado en Género y Diversidades. Trabaja desde las terapias cognitivo-conductuales y contextuales, con una mirada atenta a las dimensiones de género en cada proceso. Actualmente se forma en terapia breve estratégica y acompaña a personas adultas de forma online. Admisora y Supervisora en Contexto.Psi",
  },
  {
    id: "julieta-rosenzvit",
    name: "Lic. Julieta Rosenzvit",
    number: "M.N. 69903",
    photo: "/professionals/team/julieta-rosenzvit.webp",
    bio: "Licenciada en Psicología (UBA) de adolescentes y adultos, y se dedica también al área pericial. Con orientación psicoanalítica y residencia completa en el sistema público de salud. Diplomada en Psicología en Reproducción Humana Asistida y en Psicoanálisis y Género, con postgrado en Salud Mental Perinatal.",
  },
  {
    id: "josefina-rueda",
    name: "Lic. Josefina Rueda",
    number: "M.N. 74790",
    photo: "/professionals/team/josefina-rueda.webp",
    bio: "Lic. en Psicología (UBA) con orientación psicoanalítica y formación hospitalaria en el Hospital Álvarez. Diplomada en Prevención Comunitaria de las Violencias por Razones de Género (UNAJ), cursando la Especialización en Teoría y Práctica Psicoanalítica (UNSAM). Co-coordinadora de Casa Tekoporã, orientada a consumos problemáticos.",
  },
  {
    id: "patricia-sosa",
    name: "Lic. Patricia Sosa",
    number: "M.N. 70123",
    photo: "/professionals/team/patricia-sosa.webp",
    bio: "Psicóloga especializada en terapias contextuales con enfoque vincular, donde el lazo terapéutico es el punto de partida. Acompaña a adultxs y parejas en un espacio seguro y basado en la evidencia, siempre con perspectiva de género y derechos.",
  },
  {
    id: "alicia-demarchi",
    name: "Dra. Alicia DeMarchi",
    number: "M.N. 179772",
    photo: "/professionals/team/alicia-demarchi.webp",
    bio: "Médica (UBA, Diploma de Honor). Esp. en Psiquiatría Infantojuvenil. Diplomada en Educación Sexual Integral (UNSAM). Es psiquiatra de planta en el área de Salud Mental del Hospital de Niños Ricardo Gutiérrez y docente en la Cátedra de Salud Mental de la Facultad de Medicina (UBA). Atiende niñxs, adolescentes y adultxs, acompañando diversas problemáticas de salud mental, integrando la evaluación clínica y herramientas terapéuticas con una mirada integral.",
  },
  {
    id: "lucia-nosiglia",
    name: "Dra. Lucía Nosiglia",
    number: "M.N. 163217",
    photo: "/professionals/team/lucia-nosiglia.webp",
    bio: "Médica (UBA). Esp. en Psiquiatría de Adultos. Exresidente y Jefa de Residentes de Psiquiatría del Hospital Rivadavia. Maestranda en Psicoanálisis (UBA). Diplomada en Uso de Cannabis en la Salud. Con formación en Terapia Dialéctico Conductual (DBT).  Fue psiquiatra de Urgencias y docente en cursos de formación de posgrado para residentes.",
  },
  {
    id: "daniela-lopez",
    name: "Lic. Daniela Lopez",
    number: null,
    photo: "/professionals/team/daniela-lopez.webp",
    bio: "Especialista en Psicología Clínica. Psicóloga de planta en el Hospital F. J. Muñiz (CABA), con formación en género y psico-oncología.",
  },
  {
    id: "magali-jurnet",
    name: "Lic. Magalí Jurnet",
    number: "M.N. 8250",
    photo: "/professionals/team/magali-jurnet.webp",
    bio: "Lic. en Nutrición (UBA). Prof. en Nutrición (USAL). Docente de “Psicología de la Nutrición” en la UBA. Es nutricionista en distintas instituciones y atiende con foco en Desórdenes del comportamiento alimentario. Fue colaboradora del dispositivo de Desórdenes del Comportamiento Alimentario del Hospital Jose T. Borda y Cofundadora del Capitulo “Abordaje Interdisciplinario de los desordenes del comportamiento alimentario” (AASM).",
  },
  {
    id: "melanie-salem",
    name: "Lic. Melanie Salem",
    number: "M.N. 72090",
    photo: "/professionals/team/melanie-salem.webp",
    bio: "Lic. en Psicología de adolescentes y adultxs, con orientación psicoanalítica. Formada en Psicología del Deporte, evaluaciones psicotécnicas y ámbito pericial forense.",
  },
  {
    id: "luciano-varela",
    name: "Dr. Luciano Varela",
    number: "M.N. 181476",
    photo: "/professionals/team/luciano-varela.webp",
    bio: "Médico psiquiatra (Universidad Nacional del Litoral; residencia en Hospital José T. Borda y especialización en la UBA). Acompaña tratamientos psicofarmacológicos de adultxs, apostando siempre a la construcción interdisciplinaria en cada caso. Su clínica se orienta desde el psicoanálisis lacaniano.",
  },
];

const admissionIds = ["francisco-herzberg", "camila-larocca", "brenda-lopatka", "victoria-nunez", "veronica-percara", "josefina-rueda"];
export const admissions = admissionIds.map((id) =>
  professionals.find((professional) => professional.id === id)
).filter(Boolean);